/**:
  ros__parameters:
    # nmea_tcpclient_driver parameters
    # port: "/dev/rfcomm0"
    # port: "tcp://localhost:1111"
    # ip: "127.0.0.1"
    ip: "localhost"
    port: 1111
    # baud: 230400
    frame_id : "base_link"
    # useRMC : true

navsat_transform_node:
  ros__parameters:
    frequency: 50.0
    magnetic_declination_radians: 0.0
    yaw_offset: 1.5707963
    zero_altitude: true
    broadcast_cartesian_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: false
    delay: 10.0
    broadcast_cartesian_transform_as_parent_frame: true
