nmea_tcp_driver_node:
  ros__parameters:
    port: 1111
    frame_id : "base_link"

navsat_transform_node:
  ros__parameters:
    frequency: 50.0
    magnetic_declination_radians: 0.0
      #yaw_offset: -1.5707963
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_cartesian_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: true
    wait_for_datum: false             # GPS基準点が確定するまで待機
    # delay: 3.0                       # 遅延を短縮
    broadcast_cartesian_transform_as_parent_frame: true
